spring.datasource.url=jdbc:mysql://localhost:3306/expense_tracker
spring.datasource.username=root
spring.datasource.password=NCT127@dream

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

server.port=8080

# JWT
jwt.secret=U2VjdXJlSldUU2VjcmV0S2V5MTIzIT8kQCMkKiYoQmFzZTY0RW5jb2RlZFN0cmluZyFAMjAyNS1Mb25nLVNlY3VyZS1LZXk6U2FmZUFuZFN0cm9uZw==
jwt.expirationMs=86400000
